name: build-and-test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-windows:
    strategy:
      matrix:
        ocaml-compiler:
          - ocaml.5.0.0,ocaml-option-mingw
          - ocaml.5.1.1,ocaml-option-mingw

    runs-on: windows-latest

    env:
      QCHECK_MSG_INTERVAL: '60'

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: |
            dra27: https://github.com/dra27/opam-repository.git#windows-5.0
            default: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
            standard: https://github.com/ocaml/opam-repository.git

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Test
        run: opam exec -- dune runtest
